import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NextAuthProvider from "@/providers/NextAuthProvider";
import TanstackProvider from "@/providers/TanstackProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <NextAuthProvider>
            <Navbar />
            {children}
          </NextAuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
