import "./globals.css";
import Navbar from "../components/Navbar";
import NextAuthProvider from "../providers/NextAuthProvider";
import TanstackProvider from "../providers/TanstackProvider";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <NextAuthProvider>
            <Navbar />
            {children}
            <ToastContainer/>
          </NextAuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
